spring.application.name=laptopshop

# config database
# config database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL kết nối lên Cloud Aiven
spring.datasource.url=jdbc:mysql://mysql-chubinh-chutienbinh060205-hihilang.h.aivencloud.com:26257/laptopshop?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_YZw-2aVMgPLNRNdIv-F

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# config spring security
spring.security.user.name=chubinh
spring.security.user.password=123456

# config file upload

spring.servlet.multipart.max-file-size=100MB

# Tổng kích thước cả các trường và file

spring.servlet.multipart.max-request-size=100MB

# Tăng giới hạn cho cả request (bao gồm cả text/JSON body)

server.jetty.max-http-form-post-size=10MB

server.tomcat.max-http-form-post-size=10MB


# Việc này giúp hàm UploadService của bạn đọc trực tiếp đường dẫn này từ file cấu hình
# Dùng dấu gạch chéo / cho chuẩn đường dẫn Spring
upload.directory=D:/Spring/laptopshop/uploads/

# Cấu hình cloudinary
cloudinary.cloud-name=dbtbj5s8w
cloudinary.api-key=386422764289541
cloudinary.api-secret=mPewAja1mvna9PuuhAcrTLLeYoE