spring.application.name=laptopshop

# config database
# config database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL kết nối lên Cloud Aiven
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# config spring security
spring.security.user.name=admin
spring.security.user.password=12345678

# config file upload

spring.servlet.multipart.max-file-size=100MB

# Tổng kích thước cả các trường và file

spring.servlet.multipart.max-request-size=100MB

# Tăng giới hạn cho cả request (bao gồm cả text/JSON body)

server.jetty.max-http-form-post-size=10MB

server.tomcat.max-http-form-post-size=10MB


# Việc này giúp hàm UploadService của bạn đọc trực tiếp đường dẫn này từ file cấu hình
# Dùng dấu gạch chéo / cho chuẩn đường dẫn Spring
# upload.directory=D:/Spring/laptopshop/uploads/


# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}